name: 'Gansik-Backend'
services:
  db:
    image: mysql:8
    container_name: gansik-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gansik
    ports:
      - "3307:3306"
    networks:
      - gansik-network
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: gansik-redis
    ports:
      - "6379:6379"
    networks:
      - gansik-network
    volumes:
      - redis_data:/data

  app:
    image: gansikapp:v1
    container_name: gansik-app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
      - "9292:9292"
    networks:
      - gansik-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gansik
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

networks:
  gansik-network:

volumes:
  db_data:
  redis_data:
